dist: trusty
sudo: false

language: node_js
node_js:
  - '12'

branches:
  only:
    - master

addons:
  chrome: stable
  sonarcloud:
    organization: "smartmapperproject"
    token: $SONAR_TOKEN

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox --code-coverage
  - sonar-scanner

after_success:
  - cat ./coverage/SmartMapper/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email:
    recipients:
      - smartmapperproject@gmail.com
    on_success: always
    on_failure: always
